---
title: USC Center for Health Data Journalism R lessons
engine: knitr
format: live-html
webr:
  packages:
    - dplyr
---

{{< include _extensions/r-wasm/live/_knitr.qmd >}}


Andrew Ba Tran [andrew.tran\@washpost.com]{.email} and John Harden [john.harden\@washpost.com]{.email}

## Getting Started

Learning to code with a language like R takes some time and effort on your part. We'll be covering a lot of foundation material this week, and sometimes this can feel like a firehouse of obscure information (e.g. what is an atomic vector and how is that different from a list) that you don't know what to do with yet. If you feel that way, that's OK! You will most likely have to go back and look this stuff up again. But it will help you get started today as we start flexing those coding muscles. This site is a resource for you to refer back to.

You should expect to feel some frustration, because everybody does. Frustration is OK so long as you can persevere through it. When you finally solve the problem and your code works it's a GREAT feeling.

## Get the files

## Before we move on, run these lines in console


```
install.packages(c("usethis", "tidyverse", "remotes"))

usethis::use_course("https://github.com/r-journalism/chjr_24_class/archive/master.zip")
```

This will download the [class files](https://github.com/r-journalism/chjr_24_class/tree/main) that will accompany the in-person part of the course.

#### Day 1: Intro to R and RStudio
- [Slides](https://r-journalism.github.io/chjr_24_class/01_intro_to_r_rstudio.html#/title-slide)
- [Intro to R and RStudio](https://r-journalism.github.io/chjr_24/getting_started/r_and_rstudio.html)
- [Syntax and R Basics](https://r-journalism.github.io/chjr_24/getting_started/syntax_r_basics.html)
- [Importing, exporting data](https://r-journalism.github.io/chjr_24/getting_started/importing_exporting.html)

#### Day 2: Wrangling data
- [Slides](https://r-journalism.github.io/chjr_24_class/02_wrangling_data.html)
- [Exploring, arrange, count](https://r-journalism.github.io/chjr_24/wrangling/explore_arrange.html)
- [Filter, Select](https://r-journalism.github.io/chjr_24/wrangling/filter_select.html)
- [Mutating and summarizing data](https://r-journalism.github.io/chjr_24/wrangling/mutate_summarize.html)

#### Day 3: Transforming data
- [Slides](https://r-journalism.github.io/chjr_24_class/03_tidying_data.html)
- [Joining data](https://r-journalism.github.io/chjr_24/tidying/joining.html)
- [Pivoting data](https://r-journalism.github.io/chjr_24/tidying/math_pivots.html)

#### Day 4: Visualizing data
- [Slides](https://r-journalism.github.io/chjr_24_class/04_visualizing_data.html)
- [Visualizing data](https://r-journalism.github.io/chjr_24/visualizing/viz.html)
- [Exploratory data visualization](https://r-journalism.github.io/chjr_24/visualizing/exploratory_viz.html)

#### Practice
-   To practice creating and working with vectors and doing simple variable assignment, use [R-Basics.Rmd](practice/R-Basics.Rmd)
-   To practice importing and the basics of data analysis (sorting, filtering, aggregating), use [Importing-and-intro-to-data-analysis.Rmd](practice/Importing-and-intro-to-data-analysis.Rmd)


#### Resources
-   [Slideshow of R Basics](https://r-journalism.github.io/chjr_24_class/01_intro_to_r_rstudio.html#/title-slide)
-   [Slideshow of Wrangling Data](https://r-journalism.github.io/chjr_24_class/02_wrangling_data.html)
-   [Slideshow of Tidying data](https://r-journalism.github.io/chjr_24_class/03_tidying_data.html)
-   [Slideshow of Vizualizing data](https://r-journalism.github.io/chjr_24_class/04_visualizing_data.html)
-   [Tidyverse documentation](https://www.tidyverse.org/): We'll be referring back to this a lot. Get used to reading documentation; it's an important skill!
-   [practice scripts](https://github.com/r-journalism/chjr_24_class/tree/main/scripts): There are exercises in the practice folder that you can work on your own time
-   [weird ggplots](https://docs.google.com/presentation/d/1KZooYWyeE0DtMmuD5hGGern0zqixIh49OC304UtYSkM/edit)
-   [ggplot2 code gallery](https://r-graph-gallery.com/ggplot2-package.html)

