---
title: Syntax and R Basics
engine: knitr
format: live-html
webr:
  packages:
    - dplyr
    - lubridate
    - stringr
    - readr
    - gradethis
resources:
  - images
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}
{{< include ../_extensions/r-wasm/live/_gradethis.qmd >}}


```{webr 2}
#| include: false
#| 


m <- "apples"

sample_df <- data.frame(id=c(1001,1002,1003,1004), name=c("Steve", "Pam", "Jim", "Dwight"), age=c(26, 65, 15, 7), race=c("White", "Black", "White", "Hispanic"))
sample_df$race <- factor(sample_df$race)
sample_df$id <- factor(sample_df$id)
sample_df$name <- as.character(sample_df$name)


years <- c(301, 978, 101)

burgers <- data.frame(id=c(60006,60007,60008,60009, 60010), name=c("Bob", "Linda", "Louise", "Tina", "Gene"), age=c(45, 44, 12, 13, 11), shirt=c("White", "Red", "Pink", "Blue", "Yellow"))
burgers$shirt<- factor(burgers$shirt)
burgers$id <- factor(burgers$id)
burgers$name <- as.character(burgers$name)

mat <- matrix(data=c(9,2,3,4,5,6), ncol=3)

patientID <- c(111, 208, 113, 408)
age <- c(25, 34, 28, 52)
sex <- c(1,2,1,1)
diabetes <- c("Type1", "Type2", "Type1", "Type1")
status <- c(1,2,3,1)

patientdata <- data.frame(patientID, age, sex, diabetes, status)
```


```{webr 3}
#| edit: false
#| output: false
#| define:
#|   - ok_reponse
library(htmltools)

ok_reponse <- function(reponse, n) {
  if (is.na(reponse)) HTML("")
  else if (reponse == n) div(HTML("Correct ✓"), style = "color: green")
  else div(HTML("Incorrect ✗"), style = "color: red")
}
```

# Data types

There's more to data than just numbers, which is what we've been working with in part 1.

But sometimes data we work with can be specified as something else, like characters and strings (text and sentences) or Boolean values like **TRUE** or **FALSE** or even dates.

## Characters

Let's assign "apples" to m.



```{webr 4}
m <- "apples"
m
```

To tell R that something is a character string, you should type the text between apostrophes, otherwise R will start looking for a defined variable with the same name. See what happens.

```{webr 5}
n <- pears
```


**Because there was no " around `pears` then R assumed that `pears` was an object to be found in the `Environment`.** And you were trying to also assign an object named `n` the same value as what you had assigned to `pears`. But it didn't exist in the environment so it failed.

That's why `"` around characters are important.

You can't do math with characters, either

```{webr 6}
m + 2
```

## Dates

Dates and times are complicated. 

R has to know that 3 o'clock comes after 2:59 and that February has 29 days in some years.

The base way to tell R that something is a date-time combination is with the function `strptime()` **Note: This is the complicated way**

```{webr 7}
date1 <- strptime(c("20100225230000", "20100226000000", "20100226010000"), format="%Y%m%d%H%M%S")
date1
```


A vector is created with `c()` and the numbers between the quotation marks are strings, because that's what the `strptim()` function requires.

That's followed by the argument **format** that defines how the character string should be read. In this instance, the year is denoted first (%Y), then the month (%M) and second (%S). You don't have to specify all of them, as long as the format corresponds to the character string.



In this course, we'll be using a less messy way to deal with dates using the package **lubridate**.

```{webr 8}
# If you don't currently have the lubridate package installed, uncomment the line below and run it

# install.packages("lubridate")

library(lubridate)

date1 <- ymd_hms(c("20100225230000", "20100226000000", "20100226010000"))
```


The function `ymd_hms()` converted the year, month, date and hour, minutes, and seconds in the string. You can go over this in more detail on [lubridate's website](https://lubridate.tidyverse.org/articles/lubridate.html).

## Factors

Okay, these are kinda complicated. They're like text but in order. All R sees is the order, not the text.

* Data structure specifying categorical (nominal) or ordered categorical (ordinal) variables
*	Tells R how to handle that variable in analyses
*	Very important and misunderstood
* Any variable that is categorical or ordinal should usually be stored as a factor.

For example, Race might be input as "White", "Black", and "Hispanic"

When importing that data in from a spreadsheet, R will most often interpret it as a **Factor**.

Run these lines of code to create a new object, a dataframe called **sample_df**

```{webr 9}
sample_df <- data.frame(id=c(1001,1002,1003,1004), name=c("Steve", "Pam", "Jim", "Dwight"), age=c(26, 65, 15, 7), race=c("White", "Black", "White", "Hispanic"))
sample_df$race <- factor(sample_df$race)
sample_df$id <- factor(sample_df$id)
sample_df$name <- as.character(sample_df$name)

sample_df
```


[](images/sample_df.png?class=shadow){width=40%}

Let's take a look at the structure behind a dataframe we've created.

We'll use the function `str()` which is short for **structure**.

```{webr 10}
str(sample_df)
```

R sees that the **Race** column is a factor variable with three levels.

Do you see the `3 1 3 2` numbers at the end of the line?

```{webr 11}
levels(sample_df$race)
```


This means that R groups statistics by these levels.

```{webr 12}
summary(sample_df$race)
```


Internally, R stores the integer values 1, 2, and 3, and maps the character strings in alphabetical order to these values. 1=Black, 2=Hispanic, and 3=White.

Why is this important to know?

Journalists are less concerned by factors and will often find themselves converting factors to strings and characters. But when you reach the point that you are wanting to create models and linear regressions then you'll be happy that it's an option.


*Most odd quirks when it comes to R can be traced back to the fact that R was created by and for statisticians. R has grown a lot since then and the community has helped make it evolve to handle data the way we are more used to. But some habits die hard and are ingrained.*

## Converting between the different types

Here's a warning.

* You can convert factors into strings.

```{webr 13}
sample_df$race
as.character(sample_df$race)
```


* You can convert strings into factors

```{webr 14}
sample_df$name
factor(sample_df$name)
```

* You **cannot** convert factors into numbers.

```{webr 15}
sample_df$id
as.numeric(sample_df$id)
```

Because R stores **Factors** as **Integer** values.

You must convert factors into characters first *before* converting it to numbers.

So you can nest it.

```{webr 16}
sample_df$id
as.numeric(as.character(sample_df$id))
```

*It's okay if you don't fully understand this next section. It's pretty advanced. I give you permission to skip down to **Your turn:**.*


## Vectors

A **vector** is a sequence of data elements of the same basic type. The parts that consist of a vector are called **components** or **elements**.

```{webr 17}
vec1 <- c(1,4,6,8,10)
vec1
```

A vector `vec` is explicitly constructed by the concatenation function `c()`.

```{webr 18}
vec1[5]
```

Elements in vectors can be addressed by standard `[i]` indexing

```{webr 19}
vec1[3] <- 12
vec1
```

One of the elements in the array is replaced with a new number. 

```{webr 20}
vec2 <- seq(from=0, to=1, by=0.25)
vec2
```

This shows another useful way of creating a vector: the `seq()` or sequence function.

```{webr 21}
sum(vec1)
```


## Your turn


Challenge yourself with some exercises.

### Objects

Assign the number 17 to the object `ub`.

```{webr yourturn1a}
#| exercise: ex_1
ub __ __

ub
```

::: {.solution exercise="ex_1"}

#### Solution

`<-` is the assigner code


```{webr yourturn1b}
#| exercise: ex_1
#| solution: true
ub <- 17

ub
```

:::

```{webr yourturn1c}
#| exercise: ex_1
#| check: true
gradethis::grade_this_code()
```


### Vectors

Create an array of numbers: 301, 978, and 101.

Assign it to the object `years`.


```{webr ar1a}
#| exercise: ex_2
years #replace this with your code 

years
```

```{webr ar1b}
#| exercise: ex_2
#| solution: true
years <- c(301, 978, 101)

years
```

```{webr ar1c}
#| exercise: ex_2
#| check: true
gradethis::grade_this_code()
```



### Functions

What’s the average of the array of numbers assigned to `years`”`?


```{webr fu1}
#| exercise: fu1
    (years)

# what function() gives you the average? or another word for average?
```

```{webr fu1-solution}
#| exercise: fu1
#| solution: true
mean(years)
```

```{webr fu1-check}
#| exercise: fu1
#| check: true
gradethis::grade_this_code()
```

## Classes

Take a look at the structure of the object `burgers`:

```{webr burgers, exercise=TRUE}
#| exercise: burgers
   (burgers)
#do you remember what the name of the function is to look at the structure of an object in R?
```

```{webr burgers-solution}
#| exercise: burgers
#| solution: TRUE
str(burgers)
```

```{webr burgers-check}
#| exercise: burgers
#| check: true
gradethis::grade_this_code()
```

**What kind of class is the variable id?**

```{ojs}
//| echo: false
mutable ok_reponse = (reponse, n) => { return html`Loading...` };
viewof reponse = Inputs.radio(
  new Map([
    ["character", 1],
    ["number", 2],
    ["factor", 3],
    ["date", 4]
  ])
);
ok_reponse(reponse, 3);
```


## Matrices

**Matrices** are two-dimensional vectors.

It looks like this.

```{webr matrix}
mat <- matrix(data=c(9,2,3,4,5,6), ncol=3)
mat
```

The argument `data` specifies which numbers should be in the matrix.

Use either `ncol` to specify the number of columns or `nrow` to specify the number of rows.

Matrix operations are similar to vector operations.

Take a look at the output. Do you notice the numbers and commas in brackets that look like [1,] or [,2]?

If you've ever played [Battleship](https://www.incpartservices.com/wp-content/uploads/2019/06/battleship.jpeg) then those numbers represent coordinates in the grid. It's always **[R(ow),C(column)]**. I remember it as "Let's get ready to **[Ro,Ck]**

For example: 

```{webr matrix2}
mat[1,2]
```

This is a Base R method to pull the value from the first row and second column in the grid, which is **3**.

Elements of a matrix can be addressed in the usual way.

```{webr matrix3}
mat[2,1]
```

When you want to select a whole row, you leave the spot for the column number empty and vice versa for the columns.

```{webr matrix4}
mat[,3]
```

## Data frames

If you're used to working with spreadsheets, then *data frames* will make the most sense to you in R.

This is how to create a data frame from vectors. You don't have to fully understand this at this point-- the data you'll be working with will come pre-structured if you're importing spreadsheets.


```{webr df1}
patientID <- c(111, 208, 113, 408)
age <- c(25, 34, 28, 52)
sex <- c(1,2,1,1)
diabetes <- c("Type1", "Type2", "Type1", "Type1")
status <- c(1,2,3,1)

patientdata <- data.frame(patientID, age, sex, diabetes, status)
patientdata
```

But this is what's happening. A set of vectors are being created and a function called `data.frame()` joins them together into a data frame structure.

What if we only want to columns: `patientID` and `age`?

**How to pull elements from a data frame:**

There are several ways, but one way is to know what number columns they are in the dataframe (kind of like the Battleship method). We know `patientID` and `age` are columns 1 and 2. 

This is how to narrow down to those columns only:

```{webr}
# a : means "through"
patientdata[1:2]

# So 1:2 means 1 through 2
```

Another way is if you know the column names.

The Base R way involves using `c()` and brackets.

```{webr}
patientdata[c("diabetes", "status")]
```

## Dollar signs

If you want to look at a specific vector in a dataframe, then you can get to it by first typing out the dataframe object name and column name separated by a `$` sign.

```{webr}
patientdata$age
```

**Doing math on vectors in a dataframe:**

Instead of using `mean(patientdata[,2])`, you can select the column `age` from the `patientdata` data frame with the `$` sign.

```{webr}
mean(patientdata$age)
```

## Lists

Another basic structure in R is a *list*. 

The main advantage of lists is that the "columns" they're not really ordered in columns any more, but are more of a collection of vectors) don't have to be of the same length, unlike matrices and data frames.

Kind of like JSON files are structured.

```{webr}
g <- "My First List"
h <- c(25, 26, 18, 39)
# The line below is creating a matrix that's 5 rows deep of numbers 1 through(":") 10
j <- matrix(1:10, nrow = 5) 
k <- c("one", "two", "three")
mylist <- list(title = g, ages = h, j, k)   
```

This is how a list would appear in the work space

```{webr}
names(mylist)
```

How to find out what's in the list

```{webr}
mylist[[2]] 

mylist[["ages"]][[1]]
```

The code above extracts data from the list

```{webr}
mylist$age + 10
```

How to refer to and use the numbers in the example list

## Functions applied to dataframes

Let's start with the `sample_df` dataframe again below.

```{webr}
# Run the lines of code below
sample_df <- data.frame(id=c(1001,1002,1003,1004), name=c("Steve", "Pam", "Jim", "Dwight"), age=c(26, 65, 15, 7), race=c("White", "Black", "White", "Hispanic"))
sample_df$name <- as.character(sample_df$name)
sample_df
```

**The following functions may not seem like they have much use now but we're going to need to understand them by week 3 when we do more advanced R programming.**

`length(x)` - Find out how many things there are in an object or array

```{webr}
length(sample_df$name)
```

`nchar(x)` - If **x** is a string, finds how how many characters there are 

```{webr}
sample_df$name[1]
nchar(sample_df$name[1])
```

`dim(x)` - Gives the dimensions of **x**
```{webr}
dim(sample_df)
```

`ncol(x)` - Counts the number of columns

```{webr ncol}
ncol(sample_df)
```

`nrow(x)` - Returns the number of rows of **x**

```{webr nrow}
nrow(sample_df)
```

`str(x)` - Returns the structure of **x**

```{webr str}
str(sample_df)
```

`summary(x)` - Summarizes the object as understood by R

```{webr}
summary(sample_df)
```


`View(x)` - A command to open the object to browse in RStudio

This won't work through this browser exercise, but it's nice to have for later when you're working in RStudio.

```{r view, eval=F}
View(sample_df)
```

`rm(x)` - Removes **x**

```{webr}
rm(sample_df)
sample_df
```

## Your turn again

### Pulling a column of data

Consider this data frame **burgers**

```{webr burger_show}
burgers
```

How do you refer to the the *shirt* variable/column with the bracket method **[]**?


```{webr v1}
#| exercise: v1
# Add to the line below 
burgers
```

```{webr v1-solution}
#| exercise: v1
#| solution: true
burgers[,4]
```

```{webr v1-check}
#| exercise: v1
#| check: true
gradethis::grade_this_code()
```

How do you refer to the the *shirt* variable/column with $?

```{webr v2}
#| exercise: v2

# Add to the line below 
burgers
```

```{webr v2-solution}
#| exercise: v2
#| solution: true
burgers$shirt

```

```{webr v2-check}
#| exercise: v2
#| check: true
gradethis::grade_this_code()
``` 



### Pulling a row of data

Extract entire row for Linda using [].

```{webr v4}
#| exercise: v4

# Add to the line below 
burgers
```


```{webr v4-solution}
#| exercise: v4
#| solution: true
burgers[2,]
```   

```{webr v4-check}
#| exercise: v4
#| check: true
gradethis::grade_this_code()
```   


### Converting data classes

Convert the *id* variable of the **burgers** data frame to numeric.


```{webr v3}
#| exercise: v3
# Add to the line below 
burgers$id <- 
burgers$id
class(burgers$id)
```


```{webr v3-solution}
#| exercise: v3
#| solution: true
burgers$id <- as.numeric(as.character(burgers$id))
burgers$id
class(burgers$id)
```   


```{webr v3-check}
#| exercise: v3
#| check: true
check_this_code()
```   


*Note:* Is the answer the same as above (correct) or is it 1-5 (false)? 

